name: Update AGE in README

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht UTC

  workflow_dispatch: # Ermöglicht manuelles Triggern der Action
          
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract age from README
        id: get_current_age
        run: |
          current_age=$(grep -oP '(?<=<!--AGE_PLACEHOLDER-->)[0-9]+' README.md || echo "")
          if [ -z "$current_age" ]; then
            echo "Error: Could not extract current age from README.md."
            exit 1
          fi
          echo "current_age=$current_age" >> $GITHUB_ENV

      - name: Calculate age
        id: calculate_age
        run: |
          birthdate="2004-01-16"
          current_date=$(date +%Y-%m-%d)
          birth_year=$(date -d "$birthdate" +%Y)
          current_year=$(date -d "$current_date" +%Y)
          age=$((current_year - birth_year))
          if [ $(date -d "$current_date" +%m%d) -lt $(date -d "$birthdate" +%m%d) ]; then
            age=$((age - 1))
          fi
          echo "new_age=$age" >> $GITHUB_ENV

      - name: Update README
        run: |
          new_age=${{ steps.calculate_age.outputs.age }}
          current_age=${{ steps.get_current_age.outputs.age }}
          if [ "$new_age" != "$current_age" ]; then
            sed -i "s/<!--AGE_PLACEHOLDER-->$current_age/<!--AGE_PLACEHOLDER-->$new_age/" README.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Age automatically updated to $new_age years. Happy birthday!"
            git push
          else
            echo "Age has not changed. No commit required."
          fi
