name: Age Update README

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht UTC

  workflow_dispatch: # Ermöglicht manuelles Triggern der Action
          
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v2

      - name: Aktuelles Alter aus README extrahieren
        id: get_current_age
        run: |
          current_age=$(grep -oP '(?<=<!--AGE_PLACEHOLDER-->)[0-9]+' README.md || echo "")
          if [ -z "$current_age" ]; then
            echo "Fehler: Konnte aktuelles Alter nicht aus README.md extrahieren."
            exit 1
          fi
          echo "::set-output name=age::$current_age"

      - name: Alter berechnen
        id: calculate_age
        run: |
          birthdate="2000-01-01" # Ersetze dies durch dein tatsächliches Geburtsdatum
          current_date=$(date +%Y-%m-%d)
          birth_year=$(date -d "$birthdate" +%Y)
          current_year=$(date -d "$current_date" +%Y)
          age=$((current_year - birth_year))
          if [ $(date -d "$current_date" +%m%d) -lt $(date -d "$birthdate" +%m%d) ]; then
            age=$((age - 1))
          fi
          echo "::set-output name=age::$age"

      - name: README aktualisieren
        run: |
          new_age=${{ steps.calculate_age.outputs.age }}
          current_age=${{ steps.get_current_age.outputs.age }}
          if [ "$new_age" != "$current_age" ]; then
            sed -i "s/<!--AGE_PLACEHOLDER-->$current_age/<!--AGE_PLACEHOLDER-->$new_age/" README.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Alter automatisch aktualisiert auf $new_age Jahre"
            git push
          else
            echo "Alter hat sich nicht geändert. Kein Commit erforderlich."
          fi
