# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: GitHub Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule:
      - cron: "0 0 * * *"
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:

      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:

          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

          token: ${{ secrets.METRICS_TOKEN }}
          base: ""

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          
          retries: 3
          retries_delay: 300

