# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: GitHub Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule:
      - cron: "0 0 * * *"
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:

      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Leetcode Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:

          output_action: commit
          committer_branch: metrics
          committer_message: "chore: update leetcode metrics"
          
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: "metrics.leetcode.svg"

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          retries: 3
          retries_delay: 300

      - name: Languages Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:

          output_action: commit
          committer_branch: metrics
          committer_message: "chore: update languages metrics"
          
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: "metrics.languages.svg"

          user: Laubfrosch49
          plugin_languages: yes
          plugin_languages_colors: 0:#50b337, 1:#3f822c, 2:#34572a, 3:#22401a, 4:#122b18, 5:#0b172b, 6:#241b0e 7:#664a2e
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          
          retries: 3
          retries_delay: 300

